### ISSUE TITLE
subs disappear

### ISSUE THREAD

**Issue by ghost** [noembryo/Subber#1]
when i add a subtitle to subber they just disappear from the list they're in, once i press 'check'.
if i add 1 or 10....no matter. they disappear. I use the newest version.

**Comment by noembryo** [comment]
This is the normal behavior.
If the filename of the subtitle does not match the filename of a video file, then its impossible to upload the sub (no video file hash can be computed)..

**Comment by ghost** [comment]
i should have the video file in there  at all times?

**Comment by noembryo** [comment]
The only way to calculate the hash number...
